### ISSUE TITLE
50653 - CuryRate Does Not Sum Correctly In PowerBI

### ISSUE THREAD

**Issue by michaelwhiteha** [ThiagoCabral/Kanban#13]
PowerBI:
30737.84

SQL:
4

**Comment by tomkennedy22** [comment]
Hi Michael,

Was this a sum of that field? For the rate field, please do not summarize with a summation. CuryRate is not needed for GL validation anyways.

**Comment by michaelwhiteha** [comment]
Double checked and I grabbed the wrong item into PowerBI.  It looks good.
