### ISSUE TITLE
51443 - Carrier Id FIlter - Calendar

### ISSUE THREAD

**Issue by ThiagoCabral** [ThiagoCabral/Kanban#14]
Applying CArrier ID as filter the calendar for week 201708 does not match

[PXBOLHRD - Scenario 11.xlsx](https://github.com/thiagocabral/Kanban/files/1507178/PXBOLHRD.-.Scenario.11.xlsx)

**Comment by tomkennedy22** [comment]
Hi Thiago,

May have been a typo, but it looks like from the Excel sheet, the SQL statement is looking for Carriers CEXG and FLRT, in PowerBI you filtered CEXG, FLRT and GRTT.  Can you (or @michaelwhiteha ) confirm the correct filters?

**Comment by ThiagoCabral** [comment]
I am taking a look at it.

**Comment by ThiagoCabral** [comment]
The File attached had the wrong SQL.
The results are the same. I jus copied there the wrong SQL.
![total](https://user-images.githubusercontent.com/22477978/33289742-288e8c06-d386-11e7-9a0e-4e341df5d028.PNG)
![sql](https://user-images.githubusercontent.com/22477978/33289768-3d32a2c8-d386-11e7-9d0d-1aa71176335b.PNG)
[PXBOLHRD - Scenario 11-NEW.xlsx](https://github.com/thiagocabral/Kanban/files/1507645/PXBOLHRD.-.Scenario.11-NEW.xlsx)

**Comment by tomkennedy22** [comment]
@thiagocabral   I pushed some changed related to carrier numbers just a bit ago. I don't know for sure it will affect these numbers in your test. Would you mind refreshing and seeing if the numbers are different at all?

**Comment by ThiagoCabral** [comment]
@tomkennedy22  I did refresh the dashboard and the results are the same
![refresh](https://user-images.githubusercontent.com/22477978/33343740-09f4c5d2-d44c-11e7-8583-e3fc9328d35c.PNG)

**Comment by ThiagoCabral** [comment]
Retested and the number matched. Closing the issue.

I had to change the SQL according to @tomkennedy22 monthId calculation
