### ISSUE TITLE
51443 - Carrier Id FIlter - Calendar (Week Frame)

### ISSUE THREAD

**Issue by ThiagoCabral** [ThiagoCabral/Kanban#15]
selected week from 201701 - 201710 and the numbers do not mathc
[PXBOLHRD - Scenario 12.xlsx](https://github.com/thiagocabral/Kanban/files/1507185/PXBOLHRD.-.Scenario.12.xlsx)

**Comment by tomkennedy22** [comment]
Same comment as #14

**Comment by ThiagoCabral** [comment]
Retested and the number matched. Closing the issue.

I had to change the SQL according to @tomkennedy22 monthId calculation
