### ISSUE TITLE
51726 - Total ( Time Frame) 

### ISSUE THREAD

**Issue by ThiagoCabral** [ThiagoCabral/Kanban#16]
Scenario 1  - With no Filters The numbers do not match
[MB- Scenario1 .xlsx](https://github.com/thiagocabral/Kanban/files/1507820/MB-.Scenario1.xlsx)

**Comment by LilTrucker** [comment]
After reload, numbers should match. plz retest

**Comment by ThiagoCabral** [comment]
Please see the file attached with the data by day.
 It does not match for 3 specific days
 03/29/2017
 04/15/2017
 04/16/2017
[MB- Scenario1-Total Per Day.xlsx](https://github.com/thiagocabral/Kanban/files/1515631/MB-.Scenario1-Total.Per.Day.xlsx)

**Comment by LilTrucker** [comment]
Issue unresolved as of 2017-12-01
