### ISSUE TITLE
50653 - Petroleum - GL Tran Data Validation

### ISSUE THREAD

**Issue by ThiagoCabral** [ThiagoCabral/Kanban#2]
- [x] https://github.com/thiagocabral/Kanban/issues/23
- [x] https://github.com/thiagocabral/Kanban/issues/22
- [x] https://github.com/thiagocabral/Kanban/issues/4
- [x] https://github.com/thiagocabral/Kanban/issues/3

**Comment by ThiagoCabral** [comment]
https://github.com/thiagocabral/Kanban/issues/4

**Comment by michaelwhiteha** [comment]
Validation for this is done.

**Comment by michaelwhiteha** [comment]
[20171511 - Testing.Control - Petrocycle - GL Tran.xlsx](https://github.com/thiagocabral/Kanban/files/1532037/20171511.-.Testing.Control.-.Petrocycle.-.GL.Tran.xlsx)
