### ISSUE TITLE
51726 - Missing VALues on the dashboard display

### ISSUE THREAD

**Issue by ThiagoCabral** [ThiagoCabral/Kanban#21]
![fiscalweek display](https://user-images.githubusercontent.com/22477978/33332618-565cc19e-d42a-11e7-852d-8b633b0e51b7.PNG)

**Comment by LilTrucker** [comment]
Issue was most likely caused by stale data in the 'Header' table

Reloading the data now and in the process of creating a robot job

**Comment by LilTrucker** [comment]
Data is refreshed. Waiting for Confirmation from @thiagocabral

**Comment by ThiagoCabral** [comment]
FIXED :)
