### ISSUE TITLE
50653 - Acct Numbers Do Not Match

### ISSUE THREAD

**Issue by michaelwhiteha** [ThiagoCabral/Kanban#22]
SQL:
SELECT   
count(Acct) as AcctCount
,SUM(DrAmt)ASDrAmtSum
,SUM(CrAmt)ASCrAmtSum
,SUM(Qty)ASQtySum
,SUM(CuryRate)ASCuryRateSum
FROM dbo.GLTran
where GLTran.Acct = '120000'

![image](https://user-images.githubusercontent.com/25435784/33336613-1f6dea94-d436-11e7-81d0-2254f856f253.png)

**Comment by tomkennedy22** [comment]
@michaelwhiteha ,

Can you please do this one again and tell me the numbers by day? This may be a timing issue as we discussed yesterday.

**Comment by tomkennedy22** [comment]
Refresh completed as of 3:34, ready for retest.

**Comment by michaelwhiteha** [comment]
Fixed with a data refresh.
