### ISSUE TITLE
50653 - CustId Numbers Do Not Match

### ISSUE THREAD

**Issue by michaelwhiteha** [ThiagoCabral/Kanban#23]
SQL:
SELECT 
   count(LedgerID) AS CountLedgerID
   ,sum(CrAmt)      AS CrAmtSum
   ,sum(Qty)        AS QtySum
   ,sum(Units)      AS UnitsSum
   ,sum(CuryRate)   AS CuryRateSum
FROM dbo.GLTran           G
JOIN CALENDAR             C    ON C.Date = G.TranDate
left join dbo.Customer    CU   ON CU.CustId = G.ID
WHERE 
(
G.ID = 'QT0001' 
)

![image](https://user-images.githubusercontent.com/25435784/33348843-7b863de6-d45d-11e7-84b0-182ff9833fa1.png)

**Comment by tomkennedy22** [comment]
@michaelwhiteha   if your screenshot is correct, I may need you to retest this. Attached is a screenshot I just took for GLTran, summing CRAmt, DrAmt, Qty, and store on the far left. it matches your SQL values

<img width="855" alt="gltran_store1" src="https://user-images.githubusercontent.com/5054058/33349144-8fffd8a8-d45e-11e7-853d-c440fe3e8a86.PNG">


QT0001 halfway up list

**Comment by michaelwhiteha** [comment]
Fixed with a data refresh.
