### ISSUE TITLE
51726 - Coupon Filter $ metrics not workin

### ISSUE THREAD

**Issue by ThiagoCabral** [ThiagoCabral/Kanban#24]
I selected the CouponID = 111333 
and the number for:
Total Coupon Item Dollars
Total Additional Spend Dollar and units
are not matching.
[MB- Scenario8 .xlsx](https://github.com/thiagocabral/Kanban/files/1514873/MB-.Scenario8.xlsx)

**Comment by LilTrucker** [comment]
Metric was pointing at the wrong table. Try retesting

**Comment by ThiagoCabral** [comment]
Please take a look at the file below. The issue still happen with the scenario
![8b](https://user-images.githubusercontent.com/22477978/33442399-b5472a3c-d5ba-11e7-9074-7c5e513931cb.PNG)

[MB- Scenario8B.xlsx](https://github.com/thiagocabral/Kanban/files/1518670/MB-.Scenario8B.xlsx)

**Comment by LilTrucker** [comment]
Metrics should match up to No addi spend %, which still needs to be corrected.

Please update this with the latest data if possible @thiagocabral

**Comment by ThiagoCabral** [comment]
Only Additional Spend Is not matching when  a coupon is selected.
[MB- Scenario8.4.xlsx](https://github.com/thiagocabral/Kanban/files/1528056/MB-.Scenario8.4.xlsx)

**Comment by lekvan** [comment]
fixed. it should match now.
![image](https://user-images.githubusercontent.com/23304728/33578913-b0a8d592-d90d-11e7-8f7b-3782d45783d1.png)

**Comment by lekvan** [comment]
Please note that during my investigation of this, I could NOT tie source table counts to fact table.
_____________________________________________________________________________________________________

select count(distinct cd.transid)
from Hds.Pos.QT_CouponDetail cd
left join edw.pub.factpossalesdetail fd  on	cd.CouponId				= fd.CouponId 
							and cd.TransId				= fd.TransactionId
							and cd.LineItemId			= fd.TransactionLineItemId
where fd.fiscalweekid = '201740'

![image](https://user-images.githubusercontent.com/23304728/33579308-f8e10b76-d90e-11e7-9f4a-7873a35a64ff.png)


select count(distinct [transaction id])
from pub.factcouponredeems
where [fiscal week id] = '201740'

![image](https://user-images.githubusercontent.com/23304728/33579319-07dd7d94-d90f-11e7-9e7b-5a1b53b7f330.png)

**Comment by ThiagoCabral** [comment]
Tested and IT looks fine! 
@lekvan  I will open another issue so we can Verify the source.

**Comment by ThiagoCabral** [comment]
Leave a comment
