### ISSUE TITLE
51726 - YTD metrics Not Matching

### ISSUE THREAD

**Issue by ThiagoCabral** [ThiagoCabral/Kanban#25]
With no Filter and with the time frame from 201801-201816 The YTD metric does not match for:

TY NET Coupon Redeem Dollars. The other metrics that use that one as calculation they do not match either
![18003147](https://user-images.githubusercontent.com/22477978/33403403-e7edd21e-d525-11e7-891a-06a67716fcec.PNG)

**Comment by LilTrucker** [comment]
Numbers should be matching now. Please retest

![image](https://user-images.githubusercontent.com/25532370/33470978-ad32add2-d630-11e7-9f1f-af19f6516c0c.png)

**Comment by ThiagoCabral** [comment]
The numbers still not match. I Refresh the model and they still wrong.
![ytdissue](https://user-images.githubusercontent.com/22477978/33488145-564d7c00-d675-11e7-9b82-425b7bad082a.PNG)

**Comment by jordanedwaaaards** [comment]
YTD metric was missing this filter condition:             

&& 'Calendar'[Fiscal Week End Date] <= MAX ( 'Calendar'[Fiscal Week End Date] )

and was throwing off the YTD calculation by FiscalWeekId in the case where friday is split between 2 FiscalWeeks

**Comment by ThiagoCabral** [comment]
Fixed. Thanks @jordanedwaaaards 
![222](https://user-images.githubusercontent.com/22477978/33493766-c128898c-d686-11e7-9551-b070b610ca11.PNG)

**Comment by jordanedwaaaards** [comment]
You're welcome @thiagocabral
