### ISSUE TITLE
51276 - WTD\MTD\QTD\YTD - With Coupon

### ISSUE THREAD

**Issue by ThiagoCabral** [ThiagoCabral/Kanban#26]
The numbers do not match with coupon 111356
time frame 201749-201820

**Comment by ThiagoCabral** [comment]
please see the file attached with the scenarios that I'm having issues

[20173011 - Testing.Control - MARKET_BASKET -DSW.xlsx](https://github.com/thiagocabral/Kanban/files/1518714/20173011.-.Testing.Control.-.MARKET_BASKET.-DSW.xlsx)

**Comment by LilTrucker** [comment]
Couldn't find the SQL for the WTD/MTD/QTD/YTD

Did make many changes for those metrics in multiple places, so the numbers should be better now. Retest and make the SQL more obvious?

**Comment by ThiagoCabral** [comment]
@bobbywood12 
1)  I will retest it today
2) On the commented I made before yours, I included a excel file that has all the scenarios and all the results per tab. Each tab has the data and the sql.  Can that be more obvious? :) 

![file](https://user-images.githubusercontent.com/22477978/33487295-5845f6de-d672-11e7-93b6-9d86883ed701.PNG)
