### ISSUE TITLE
51726 - Dates not showing up

### ISSUE THREAD

**Issue by ThiagoCabral** [ThiagoCabral/Kanban#27]
Day range for MTD/WTD/QTD/YTD

There days that are not showing up on the dashboard but they are showing on pub.FactCouponredeems
![1](https://user-images.githubusercontent.com/22477978/33452064-89853f94-d5d6-11e7-9114-379b62222a9f.PNG)
![2](https://user-images.githubusercontent.com/22477978/33452065-899e1b72-d5d6-11e7-9d24-a2d48cdab02e.PNG)

**Comment by LilTrucker** [comment]
Issue is definitely related to missing dates in the fact table

Resolution will involve inserting a 0 record for every date that is missing in the fact table, which will allow WTD/QTD/MTD/YTD to show up
