### ISSUE TITLE
51726 - Day Range with Coupon

### ISSUE THREAD

**Issue by ThiagoCabral** [ThiagoCabral/Kanban#28]
IF a coupon selected the metrics do not match secanrio 9 and 10
![new](https://user-images.githubusercontent.com/22477978/33460682-e64095da-d5f4-11e7-9baa-475889ac9a50.PNG)
[MB- Scenario9.xlsx](https://github.com/thiagocabral/Kanban/files/1519850/MB-.Scenario9.xlsx)
[MB- Scenario10.xlsx](https://github.com/thiagocabral/Kanban/files/1519851/MB-.Scenario10.xlsx)

**Comment by LilTrucker** [comment]
SQL for testing was not filtering on only transactions with couponId 111356.

Attempted to make a fix at the SQL which filters out transactions. Please retest


DECLARE @START DateTime = '2017/06/06' ;
DECLARE @END DateTime  =  '2017/06/06'  ;
DECLARE @COUPON_ID int = 111356;

with CouponTrans as (
select distinct [Transaction Id]
from pub.FactCouponRedeems
where [Coupon Id] = @Coupon_Id
)
SELECT F.TransactionDate
,SUM(CASE WHEN [Is Coupon] = 1 AND [Coupon Id] = @COUPON_ID THEN (Dollars) ELSE 0 END)AS 'Net Coupon Redeem Dollars'
,SUM(CASE WHEN [Is Coupon] = 1 AND [Coupon Id] = @COUPON_ID THEN (Units)   ELSE 0 END)AS 'Net Coupon Redeem '
,SUM(CASE WHEN [Is Coupon] = 0 AND [Coupon Id] = @COUPON_ID THEN (Dollars) ELSE 0 END )AS 'Total Coupon Item Dollars'
,SUM(CASE WHEN [Is Coupon] = 0 AND [Coupon Id] = @COUPON_ID THEN (Units)   ELSE 0 END )AS 'Total Coupon Item Units'
,SUM(Dollars)AS 'Total MB Dollars'
,SUM(CASE WHEN [Coupon Id] IS NULL OR [Coupon Id] != @COUPON_ID THEN Dollars ELSE 0 END)AS 'Total Additional Spend Dollars'
,SUM(CASE WHEN [Coupon Id] IS NULL OR [Coupon Id] != @COUPON_ID THEN (Units)   ELSE 0 END )AS 'Total Additional Spend Units'
,SUM(Dollars)/Count(Distinct r.[Transaction Id])AS 'Average MB Dollars'
,SUM(CASE WHEN [Coupon Id] IS NULL OR [Coupon Id] != @COUPON_ID THEN (Dollars) ELSE 0 END)/Count(Distinct r.[Transaction Id])AS 'Average Additional Spend Dollars'
,ABS(SUM(CASE WHEN [Is Coupon] = 1 AND [Coupon Id] = @COUPON_ID THEN (Dollars) ELSE 0 END)/
(SUM(CASE WHEN [Is Coupon] = 0 AND [Coupon Id] = @COUPON_ID THEN (Dollars) ELSE 0 END) + 
SUM(CASE WHEN [Coupon Id] IS NULL OR [Coupon Id] != @COUPON_ID THEN Dollars ELSE 0 END)))AS 'MB Discount Dollars %'
,ABS(SUM(CASE WHEN [Is Coupon] = 0 AND [Coupon Id] = @COUPON_ID THEN (Units) ELSE 0 END)/
(SUM(CASE WHEN [Is Coupon] = 0 AND [Coupon Id] = @COUPON_ID THEN (Units) ELSE 0 END) + 
 SUM(CASE WHEN [Coupon Id] IS NULL OR [Coupon Id] != @COUPON_ID THEN (Units) ELSE 0 END)))AS 'MB Discount Units %'
  ,COUNT(Distinct r.[Transaction Id])AS 'Transactions'
FROM pub.FactCouponredeems R
join     CouponTrans       c on R.[Transaction Id] = c.[Transaction Id]
JOIN phys.FactPosSalesDetail F ON F.TransactionId= R.[Transaction Id] 
  AND F.TransactionLineItemId= R.[Transaction Line Item Id]  
WHERE F.TransactionDate BETWEEN @START AND @END
GROUP BY F.TransactionDate
ORDER BY F.TransactionDate

**Comment by ThiagoCabral** [comment]
The SQL Fix for SINGLE DAY :)Scenario 9

**Comment by ThiagoCabral** [comment]
We still have a issue for DAY RANGE Scenario 10

**Comment by ThiagoCabral** [comment]
retested and still have couple discrepancies
[MB- Scenario10 .xlsx](https://github.com/thiagocabral/Kanban/files/1529081/MB-.Scenario10.xlsx)

**Comment by ThiagoCabral** [comment]
the  Jun 8th does not match
[MB- Scenario10.3.xlsx](https://github.com/thiagocabral/Kanban/files/1532700/MB-.Scenario10.3.xlsx)

**Comment by ThiagoCabral** [comment]
@lekvan 
Please see the file attached with a bigger range
01/01/2017 - 10/18/2017
[MB- Scenario12 .xlsx](https://github.com/thiagocabral/Kanban/files/1535766/MB-.Scenario12.xlsx)
