### ISSUE TITLE
51726 - MB Discount % $ not mathcing

### ISSUE THREAD

**Issue by ThiagoCabral** [ThiagoCabral/Kanban#29]
When the total redeem dollars was fixed the issue for the MB showed up.
Scenario 4.1
[MB- Scenario4.1.xlsx](https://github.com/thiagocabral/Kanban/files/1522293/MB-.Scenario4.1.xlsx)

**Comment by jordanedwaaaards** [comment]
Changed the definition of Total NonCoupon Transaction Dollars metric from 
FROM
abs([Net Coupon Redeem Dollars]) + [Additional Spend Dollars]
TO
abs([Total Coupon Item Dollars]) + [Additional Spend Dollars]

which was affecting the denominator of MB Discount Dollars % calculation

**Comment by ThiagoCabral** [comment]
Numbers Match  - Thanks @jordanedwaaaards

**Comment by jordanedwaaaards** [comment]
You're welcome @thiagocabral
