### ISSUE TITLE
50653 - Total Number no Filter

### ISSUE THREAD

**Issue by ThiagoCabral** [ThiagoCabral/Kanban#3]
The total with no filter does not match.

[scenario 1.xlsx](https://github.com/thiagocabral/Kanban/files/1484105/scenario.1.xlsx)

**Comment by ThiagoCabral** [comment]
I retested and the issue is there still
[GL TRAN - Scenario 1A.xlsx](https://github.com/thiagocabral/Kanban/files/1493077/GL.TRAN.-.Scenario.1A.xlsx)

**Comment by michaelwhiteha** [comment]
@tomkennedy22 i did some investigation into this issue with multiple refreshes of the model and compiled a list between the SQL vs Power BI.  

It looks like there are some dates that have information in the future and starting on 10/21 in PowerBI the numbers are not matching.

**Comment by michaelwhiteha** [comment]
Hey @tomkennedy22 i did some more investigation and it looks like we're missing some acct numbers from 10/21 (the sample day i looked at) in the Power BI side of things.

Take a look at the spreadsheet.

[20171129 - GLTran.xlsx](https://github.com/thiagocabral/Kanban/files/1516108/20171129.-.GLTran.xlsx)

Is this something on our side we need to fix?

**Comment by michaelwhiteha** [comment]
No go.

[Validation.xlsx](https://github.com/thiagocabral/Kanban/files/1528246/Validation.xlsx)

**Comment by michaelwhiteha** [comment]
This is a data sync issue and is almost impossible to test for correctly.  For now, we'll close it.
