### ISSUE TITLE
51443 - Data not matching with DropState

### ISSUE THREAD

**Issue by michaelwhiteha** [ThiagoCabral/Kanban#34]
Power BI:
used all the calculation fields in the calculation table.  used the dropstate from the store dimension table.

SQL:
SELECT 
SUM(T.NetQty)/42 AS 'Barrels'
,cast((SUM(CAST(T.ExtPrice - T.ExtCostProd AS MONEY))/SUM(T.NetQty)) as decimal(6,5)) AS 'CPG'
,SUM(T.ExtCostFreight) AS 'Delivered Freight Cost'
,SUM(T.ExtBillFreight) AS 'Delivered Freight Price'
,SUM(T.ExtPrice) AS 'Delivered Product Price'
,SUM(T.UnitPrice) AS 'Delivered Unit Product Price'
,SUM(CAST (T.ExtBillFreight - T.ExtCostFreight AS MONEY)) AS 'Freight Margin'
,SUM(T.GrossQty) AS 'Gross Quantity'
,SUM(T.ExtCostProd) AS 'Lifted Product Cost'
,SUM(T.UnitCostProd) AS 'Lifted Unit Product Cost'
,SUM(T.NetQty) AS 'Net Quantity'
,SUM(CAST (T.ExtPrice - T.ExtCostProd AS MONEY)) AS 'ProductMargin'
FROM dbo.pxtran T
JOIN dbo.PXBOLHDR B ON B.DocID   = T.DocID
JOIN dbo.PXCALENDARDET  C ON C.CALDATE = B.DeliveryDate
WHERE T.status <> 'R' 
AND B.Status <> 'R' 
AND B.DOCTYPE = 'BT' 
AND B.BOLTYPE = 'DL'
and 
(
t.DROPSTATE = 'ga'
or t.DROPSTATE = 'ia'
or t.DROPSTATE = 'tx'
)

The freight calculations and CPG match but everything else does not.

**Comment by michaelwhiteha** [comment]
Screenshot:
![image](https://user-images.githubusercontent.com/25435784/33696564-73a62ce6-dac8-11e7-9ce0-d788b49bf3e2.png)

**Comment by michaelwhiteha** [comment]
After a little more investigation, this might be a timing issue of when the sql is pulled and the data refresh similar to issue 3 in GL Tran.  Can you confirm?

**Comment by michaelwhiteha** [comment]
Similar issue but this one has a fiscal month id:

PowerBI:
![image](https://user-images.githubusercontent.com/25435784/33697099-e1830b60-daca-11e7-985a-dc135763eb63.png)

SQL:
SELECT 
SUM(T.NetQty)/42 AS 'Barrels'
,cast((SUM(CAST(T.ExtPrice - T.ExtCostProd AS MONEY))/SUM(T.NetQty)) as decimal(6,5)) AS 'CPG'
,SUM(T.ExtCostFreight) AS 'Delivered Freight Cost'
,SUM(T.ExtBillFreight) AS 'Delivered Freight Price'
,SUM(T.ExtPrice) AS 'Delivered Product Price'
,SUM(T.UnitPrice) AS 'Delivered Unit Product Price'
,SUM(CAST (T.ExtBillFreight - T.ExtCostFreight AS MONEY)) AS 'Freight Margin'
,SUM(T.GrossQty) AS 'Gross Quantity'
,SUM(T.ExtCostProd) AS 'Lifted Product Cost'
,SUM(T.UnitCostProd) AS 'Lifted Unit Product Cost'
,SUM(T.NetQty) AS 'Net Quantity'
,SUM(CAST (T.ExtPrice - T.ExtCostProd AS MONEY)) AS 'ProductMargin'
FROM dbo.pxtran T
left JOIN dbo.PXBOLHDR B ON B.DocID   = T.DocID
JOIN dbo.PXCALENDARDET  C ON C.CALDATE = B.DeliveryDate
WHERE T.status <> 'R' 
AND B.Status <> 'R' 
AND B.DOCTYPE = 'BT' 
AND B.BOLTYPE = 'DL'
and 
(
t.DROPSTATE = 'ga'
or t.DROPSTATE = 'ia'
or t.DROPSTATE = 'tx'
)

--calendar
--and c.CALDATE = '1-17-2017'

--calendar range
--and c.CALDATE between '8-20-2016' and '6-2-2017'

--fiscal
and b.PerPost = '201711'

**Comment by tomkennedy22** [comment]
@michaelwhiteha , can you include the results from SQL and also screenshot of powerbi report? So I can see filters and all selections.

Thanks

**Comment by michaelwhiteha** [comment]
For the 3 drop state fiscal week of 201711

![image](https://user-images.githubusercontent.com/25435784/33725725-97f8059a-db38-11e7-87fc-d2af45d8d7cf.png)

**Comment by michaelwhiteha** [comment]
Scenario 32

[20171511 - Testing.Control - Petrocycle - PXTRAN-PXBOLHDR.xlsx](https://github.com/thiagocabral/Kanban/files/1539817/20171511.-.Testing.Control.-.Petrocycle.-.PXTRAN-PXBOLHDR.xlsx)

**Comment by tomkennedy22** [comment]
@michaelwhiteha , this is a case of the transactions having incorrect States. This is a known issue with Adam and ok.  Correct SQL below:

with Custstate as (
select CodeVal as Store, xrefval as State
FROM dbo.pxcodexref
where codeclass = 'Store' and xrefclass = 'State'
)
SELECT
SUM(T.NetQty)/42 AS 'Barrels'
,cast((SUM(CAST(T.ExtPrice - T.ExtCostProd AS MONEY))/SUM(T.NetQty)) as decimal(6,5)) AS 'CPG'
,SUM(T.ExtCostFreight) AS 'Delivered Freight Cost'
,SUM(T.ExtBillFreight) AS 'Delivered Freight Price'
,SUM(T.ExtPrice) AS 'Delivered Product Price'
,SUM(T.UnitPrice) AS 'Delivered Unit Product Price'
,SUM(CAST (T.ExtBillFreight - T.ExtCostFreight AS MONEY)) AS 'Freight Margin'
,SUM(T.GrossQty) AS 'Gross Quantity'
,SUM(T.ExtCostProd) AS 'Lifted Product Cost'
,SUM(T.UnitCostProd) AS 'Lifted Unit Product Cost'
,SUM(T.NetQty) AS 'Net Quantity'
,SUM(CAST (T.ExtPrice - T.ExtCostProd AS MONEY)) AS 'ProductMargin'
FROM dbo.pxtran T
left JOIN dbo.PXBOLHDR B ON B.DocID = T.DocID
left join custstate C ON C.Store = T.CustID
WHERE T.status <> 'R'
AND B.Status <> 'R'
AND B.DOCTYPE = 'BT'
AND B.BOLTYPE = 'DL'
and
(
   c.State = 'ga'
or c.State = 'ia'
or c.State = 'tx'
)
and b.PerPost = '201711'
