### ISSUE TITLE
Store DEvelopment - APEntryType not matching

### ISSUE THREAD

**Issue by ThiagoCabral** [ThiagoCabral/Kanban#38]
Doing total count and assuming that all the storeids from the Propertyutilities are "Paper" the numbers do not match
![apentrytype](https://user-images.githubusercontent.com/22477978/34539073-bc9d726a-f094-11e7-8b44-e64f31a52fe5.PNG)
[Store_Utilities - Testing - Copy.xlsx](https://github.com/thiagocabral/Kanban/files/1601651/Store_Utilities.-.Testing.-.Copy.xlsx)

**Comment by ThiagoCabral** [comment]
@jordanedwaaaards 
Can you make sure you get the definition of the " Paper" with QT today? So we can move forward

**Comment by jordanedwaaaards** [comment]
That’s a good idea @thiagocabral/Kanban<mailto:reply@reply.github.com>

- Jordan
512.924.2185 [Cell phone]

**Comment by ThiagoCabral** [comment]
FIXED
