### ISSUE TITLE
Store Development - Infinity and NaN Values

### ISSUE THREAD

**Issue by ThiagoCabral** [ThiagoCabral/Kanban#39]
There are still times in which the metrics show as infinity or NaN.
![store2](https://user-images.githubusercontent.com/22477978/34778551-887c7496-f615-11e7-932f-18aa304ca393.PNG)

**Comment by jordanedwaaaards** [comment]
Please retest @thiagocabral

**Comment by ThiagoCabral** [comment]
Tested and it looks good!
