### ISSUE TITLE
50653 -  Day Range Not Matching

### ISSUE THREAD

**Issue by ThiagoCabral** [ThiagoCabral/Kanban#4]
When I used a interval the GL  tran table values do not match the SQL
[scenario 5.xlsx](https://github.com/thiagocabral/Kanban/files/1484109/scenario.5.xlsx)

**Comment by ThiagoCabral** [comment]
I retested and it is not working still
[GL TRAN - Scenario 5A.xlsx](https://github.com/thiagocabral/Kanban/files/1493079/GL.TRAN.-.Scenario.5A.xlsx)

**Comment by michaelwhiteha** [comment]
I refreshed the table and it matches now.  I'll close this.
