### ISSUE TITLE
Store Development - Dollars and units = 0 but dollars per Units <>0

### ISSUE THREAD

**Issue by ThiagoCabral** [ThiagoCabral/Kanban#41]
The example below dollars and units are = 0 but the dollars per units is <>0
Thoughts?

![store3](https://user-images.githubusercontent.com/22477978/34782636-4448d1d2-f621-11e7-937d-20ddcc00f769.PNG)

**Comment by jordanedwaaaards** [comment]
I have a thought @thiagocabral  - this should be retested.

**Comment by ThiagoCabral** [comment]
TEsted!
