### ISSUE TITLE
Store Development - Crazy Dates

### ISSUE THREAD

**Issue by ThiagoCabral** [ThiagoCabral/Kanban#42]
For GL date with crazy  beg or end period, force it to zero or try to find a way to correct them
![store4](https://user-images.githubusercontent.com/22477978/34782736-844beff8-f621-11e7-9037-38a48df76420.PNG)

**Comment by jordanedwaaaards** [comment]
@thiagocabral please retest I excluded calculations for period days when the datediff > 365

**Comment by ThiagoCabral** [comment]
Tested!  It looks good
