### ISSUE TITLE
Store Development - TY and LY Values

### ISSUE THREAD

**Issue by ThiagoCabral** [ThiagoCabral/Kanban#43]
When I Select TY and LY dollars by GL date the metrics to not show up. I assume because the GL dates are different between the years. 

But when I delete GL date I still get the same blank fro LY values

Even with no filter LY is blank

![store5](https://user-images.githubusercontent.com/22477978/34794840-db5dc070-f647-11e7-8e3c-aa33784b41d8.PNG)

**Comment by jordanedwaaaards** [comment]
Working as designed @thiagocabral the LY metrics only work when you bring in a date filter (Fiscal Year Month) and you're right they do not show up for gldate because that doesn't have the same date as last year

**Comment by jordanedwaaaards** [comment]
aka no issue here move along

**Comment by ThiagoCabral** [comment]
Ok. MAke sure you include that information on the DOCUMENTaTION.,

**Comment by jordanedwaaaards** [comment]
It's there in the documentation @thiagocabral
