### ISSUE TITLE
Store DEvelopment - MEtrics Formating

### ISSUE THREAD

**Issue by ThiagoCabral** [ThiagoCabral/Kanban#45]
For consistence make sure the % Change metrics are all in #.##% format
It means 2 decimal cases.
![store6](https://user-images.githubusercontent.com/22477978/34797706-317524c2-f651-11e7-8118-032fc9237bb4.PNG)

**Comment by jordanedwaaaards** [comment]
@thiagocabral should be good to go

**Comment by ThiagoCabral** [comment]
TESTED
