### ISSUE TITLE
Store Development - TY/LY Dollars Per Unit % Change Not Matching

### ISSUE THREAD

**Issue by ThiagoCabral** [ThiagoCabral/Kanban#46]
Please see the file attached with the testing for this metric.

Because TY metrics are tested and the LY as well. I just tested the %Change using the dashboard.

![store7](https://user-images.githubusercontent.com/22477978/34798023-4e1b922c-f652-11e7-9160-5a72b1668c21.PNG)

[Issue 11.xlsx](https://github.com/thiagocabral/Kanban/files/1620589/Issue.11.xlsx)

**Comment by jordanedwaaaards** [comment]
I made the decimal places 10, so you can retest @thiagocabral

**Comment by ThiagoCabral** [comment]
MAtches now.
Should we put 3 or 4 decimal cases for the those metrics as default?

**Comment by jordanedwaaaards** [comment]
No I don't think so @thiagocabral it's good.

**Comment by ThiagoCabral** [comment]
OK
