### ISSUE TITLE
51443 - Total with no time frame

### ISSUE THREAD

**Issue by ThiagoCabral** [ThiagoCabral/Kanban#7]
The total for 4 metrics that I have the definition is not matching.
there is no trime frame selected.

Please see below the SQL I used:
SELECT	 SUM(T.NetQty)/SUM(CAST(T.ExtPrice - T.ExtCostProd AS MONEY))		AS	CPG
		,SUM(T.NetQty)														AS	NetQty
		,SUM(CAST (T.ExtPrice - T.ExtCostProd AS MONEY))					AS	ProductMargin
		,SUM(CAST (T.ExtBillFreight - T.ExtCostFreight AS MONEY))			AS	FreightMargin
FROM dbo.pxtran T
JOIN dbo.PXBOLHDR B on B.DocID = T.DocID

![total- power bi](https://user-images.githubusercontent.com/22477978/33087736-0efafbfa-ceb1-11e7-8801-324764249981.PNG)
![total](https://user-images.githubusercontent.com/22477978/33087737-0f1bd0a0-ceb1-11e7-805c-f389ac7c1650.PNG)

**Comment by ThiagoCabral** [comment]
I just re-ran after we pointed the model to 01 d and the values still not match
[PXBOLHRD - Scenario 1.xlsx](https://github.com/thiagocabral/Kanban/files/1492843/PXBOLHRD.-.Scenario.1.xlsx)

**Comment by ThiagoCabral** [comment]
If the new SQL the numbers still not matching

**Comment by ThiagoCabral** [comment]
Still not matching

**Comment by ThiagoCabral** [comment]
Please see the file attached with the data by day.
It does not match for 3 specific days 
03/29/2017
04/15/2017
04/16/2017
[MB- Scenario1-Total Per Day.xlsx](https://github.com/thiagocabral/Kanban/files/1515564/MB-.Scenario1-Total.Per.Day.xlsx)

**Comment by bobbywood12** [comment]
Move to the CORRECT workstream >:|

**Comment by LilTrucker** [comment]
Wait, this is a petroleum issue...

**Comment by ThiagoCabral** [comment]
@michaelwhiteha did you check that issue?

**Comment by ThiagoCabral** [comment]
The issue happens in 2 dates
Please see the file attached

Also there are data that has no DATE linked to it
![data](https://user-images.githubusercontent.com/22477978/33778599-ff0ab6f2-dc0e-11e7-9aef-c74e0ea34fbc.PNG)

[Scenario 1 - TOTAL.xlsx](https://github.com/thiagocabral/Kanban/files/1543461/Scenario.1.-.TOTAL.xlsx)
