### ISSUE TITLE
51443 - Single Fiscal Month Does not match

### ISSUE THREAD

**Issue by ThiagoCabral** [ThiagoCabral/Kanban#8]
I selected 201801 and the numbers do not match
Please see the result, sql and screenshot on the file attached 
[PXBOLHRD - Scenario 2.xlsx](https://github.com/thiagocabral/Kanban/files/1492876/PXBOLHRD.-.Scenario.2.xlsx)

**Comment by tomkennedy22** [comment]
Hi Thiago,

Whenever querying PXTran & PXBOLHdr, please use the following query.


SELECT B.PerPostAS 'Fiscal Month'
,SUM(T.NetQty)/42AS 'Barrels'
,SUM(CAST(T.ExtPrice - T.ExtCostProd AS MONEY))/SUM(T.NetQty)AS 'CPG'
,SUM(T.ExtCostFreight)AS 'Delivered Freight Cost'
,SUM(T.ExtBillFreight)AS 'Delivered Freight Price'
,SUM(T.ExtPrice)AS 'Delivered Product Price'
,SUM(T.UnitPrice)AS 'Delivered Unit Product Price'
,SUM(CAST (T.ExtBillFreight - T.ExtCostFreight AS MONEY))AS 'Freight Margin'
,SUM(B.GrossQty)AS 'Gross Quantity'
,SUM(T.ExtCostProd)AS 'Lifted Product Cost'
,SUM(T.UnitCostProd)AS 'Lifted Unit Product Cost'
,SUM(T.NetQty)AS 'Net Quantity'
,SUM(CAST (T.ExtPrice - T.ExtCostProd AS MONEY))AS 'ProductMargin'
FROM dbo.pxtran   T
JOIN dbo.PXBOLHDR B on B.DocID = T.DocID
where t.status <> 'R' and B.Status <> 'R' and B.DOCTYPE = 'BT' and B.BOLTYPE = 'DL'
  and B.PerPost = '201801'
GROUP BY B.PerPost


The filters of "where t.status <> 'R' and B.Status <> 'R' and B.DOCTYPE = 'BT' and B.BOLTYPE = 'DL'" will fix some of the data discrepancies, I'm hoping.

Thanks!

**Comment by ThiagoCabral** [comment]
With the new WHERE clause only GROSS QTY is not matching
